# *x1 = x1 + 2x2 + x3 + u
# *x2 = x2 + 3x3 - u
# *x3 = x1 - x2 - x3

# x = (x1 x2 x3)

In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2, 1], [0, 1, 3], [1, -1, -1]])
A

array([[ 1,  2,  1],
       [ 0,  1,  3],
       [ 1, -1, -1]])

In [5]:
B = np.array([[1],[-1],[0]])
B

array([[ 1],
       [-1],
       [ 0]])

In [6]:
AB = A.dot(B)
AB

array([[-1],
       [-1],
       [ 2]])

In [7]:
A2B = A.dot(AB)
A2B

array([[-1],
       [ 5],
       [-2]])

In [8]:
from numpy import linalg as LA

In [39]:
K = np.array([ 
    [B[0][0], AB[0][0], A2B[0][0]], # 0
    [B[1][0], AB[1][0], A2B[1][0]], # 1
    [B[2][0], AB[2][0], A2B[2][0]], # 2
])
K

array([[ 1, -1, -1],
       [-1, -1,  5],
       [ 0,  2, -2]])

In [20]:
LA.matrix_rank(K)

3

In [100]:
LA.det(K)

-4.0