<h4><i>Пример 1. </i>Исследовать на наблюдаемость систему:</h4>
\begin{aligned}
\left\{ 
\begin{array}{cl}
\dot{x_{1}}&= \ x_{2} \\
\dot{x_{2}}&= \ \mathbb{u}
\end{array}
\right.
\end{aligned}
\begin{aligned}
y = x_{1} = Hx
\end{aligned}

In [70]:
import numpy as np
from numpy import linalg as LA

In [71]:
A = np.array([ 
    [0, 1], 
    [0, 0] 
])
B = np.array([ 
    [0], 
    [1] 
])
H = np.array([ 1, 0 ])

In [72]:
AB = A.dot(B)
AB

array([[1],
       [0]])

In [73]:
# K = (B, AB)

K = np.array([
    [ B[0][0], AB[0][0] ],
    [ B[1][0], AB[1][0] ]
])
K

array([[0, 1],
       [1, 0]])

In [74]:
LA.det(K)

-1.0

In [75]:
LA.matrix_rank(K)

2

<h4>проверка на наблюдаемость:</h4>

In [76]:
HA = H.dot(A)
HA

array([0, 1])

In [77]:
res_m = np.array([
    H,
    HA
])
res_m

array([[1, 0],
       [0, 1]])

In [78]:
LA.matrix_rank(res_m)

2

In [79]:
LA.det(res_m)

1.0

<i>Det != 0; rank = n. Система наблюдаема по критерию Калмана.</i>

<h4>Пример 2.</h4>

\begin{aligned}
y = x_{2}
\end{aligned}

In [80]:
H2 = np.array([ 0, 1 ])
H2

array([0, 1])

In [81]:
HA2 = H2.dot(A)
HA2

array([0, 0])

In [82]:
res_m2 = np.array([
    H2,
    HA2
])
res_m2

array([[0, 1],
       [0, 0]])

In [83]:
LA.matrix_rank(res_m2)

1

In [84]:
LA.det(res_m2)

0.0

<h4>Система не наблюдаема.</h4>

<h4>Пример 3.</h4>

\begin{aligned}
\left\{ \begin{array}{cl}
\dot{x_{1}} & = \ x_{1}-x_{2}-x_{3} \\
\dot{x_{2}} & = \ -x_{1}+x_{2}+\mathbb{u} \\
\dot{x_{3}} & = \ 2x_{1}-3x_{3}-2\mathbb{u}
\end{array} \right.
\end{aligned}
\begin{aligned}
y = x_{1}+x_{2}
\end{aligned}

In [85]:
A_3 = np.array([
    [ 1, -1, -1],
    [-1,  1,  0],
    [ 2,  0, -3]
])
A_3

array([[ 1, -1, -1],
       [-1,  1,  0],
       [ 2,  0, -3]])

In [86]:
B_3 = np.array([
    [ 0],
    [ 1],
    [-2]
])
B_3

array([[ 0],
       [ 1],
       [-2]])

In [87]:
AB_3 = A_3.dot(B_3)
AB_3

array([[1],
       [1],
       [6]])

In [88]:
A2B_3 = A_3.dot(AB_3)
A2B_3

array([[ -6],
       [  0],
       [-16]])

In [89]:
K_3 = np.array([ 
    [B_3[0][0], AB_3[0][0], A2B_3[0][0]],
    [B_3[1][0], AB_3[1][0], A2B_3[1][0]],
    [B_3[2][0], AB_3[2][0], A2B_3[2][0]]
])
K_3

array([[  0,   1,  -6],
       [  1,   1,   0],
       [ -2,   6, -16]])

In [90]:
LA.det(K_3)

-31.999999999999986

In [91]:
LA.matrix_rank(K_3)

3

In [92]:
H_3 = np.array([1, 1, 0])
H_3

array([1, 1, 0])

In [93]:
HA_3 = H_3.dot(A_3)
HA_3

array([ 0,  0, -1])

In [94]:
HA2_3 = HA_3.dot(A_3)
HA2_3

array([-2,  0,  3])

In [95]:
res_m3 = np.array([
    H_3,
    HA_3,
    HA2_3
])
res_m3

array([[ 1,  1,  0],
       [ 0,  0, -1],
       [-2,  0,  3]])

In [96]:
LA.matrix_rank(res_m3)

3

In [97]:
LA.det(res_m3)

2.0

<h4>Система наблюдаема по критерию Калмана.</h4>