<h4>Алгоритм решения задачи стабилизации для системы:</h4>

\begin{aligned}
\dot{x} = A_{x} + B_{u}
\end{aligned}
\begin{aligned}
x \in R^n, u \in R
\end{aligned}

<h5>1. Запишем матрицу K=(k1, k2, ... kn)</h5>

<h5>2. Вычислим F = A + BK</h5>

<h5>3. Запишем характеристический многочлен матрицы F</h5>

\begin{aligned}
P\left(\lambda\right)=\det\left(F-\lambda I\right)=C_{n}\lambda^n+C_{n}-1^{\lambda^{R-1}}+...+C_{1}\lambda+C_{0}
\end{aligned}

<h5>4. Коэффициенты cj зависят от k1,k2...kn.</h5>
<h5>Подберем k1,k2...kn так, чтобы все корни многочлена P(lambda) имели отрицательные вещественные части</h5>

<h6>Например, выберем k1, k2, ... kn из условия:</h6>

\begin{aligned}
\lambda1=\lambda2= ... \lambda n=-1
\end{aligned}
<h6>т.е.</h6>

\begin{aligned}
\pm \left( \lambda + 1 \right)^n\equiv \mathrm{P}\left( \lambda \right)
\end{aligned}

<h5>5. Тогда управление с обратной связью u=Kx решает задачу стабилизации системы (1)</h5>

<h6>Пример:</h6>

\begin{aligned}
\left\{ 
\begin{array}{cl}
\dot{x_1} & = x_2 \\
\dot{x_2} & = \mathbb{u}
\end{array} 
\right.
\end{aligned}
\begin{aligned}
n = 2
\end{aligned}

<h6>K = (k1, k2)</h6>

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([ 
    [0, 1],
    [0, 0]
])
A

array([[0, 1],
       [0, 0]])

In [3]:
B = np.array([ [0], [1] ])
B

array([[0],
       [1]])

In [4]:
K = np.array([ ['-1', '-2'] ], dtype='int')
K

array([[-1, -2]])

\begin{aligned}
F=\begin{pmatrix}0&1\\0&0\end{pmatrix}+\begin{pmatrix}0\\1\end{pmatrix}\begin{pmatrix}k_1&k_2\end{pmatrix}=\begin{pmatrix}0&1\\k_1&k_2\end{pmatrix}
\end{aligned}

In [5]:
F = A + B.dot(K)
F

array([[ 0,  1],
       [-1, -2]])

In [6]:
I = np.eye(2, dtype='int')
lmbd = -1
F - I.dot(lmbd)

array([[ 1,  1],
       [-1, -1]])

In [7]:
Plmbd = LA.det(F - I.dot(lmbd))
Plmbd

0.0

\begin{aligned}
P\left(\lambda\right)=\begin{vmatrix}-\lambda&1\\k_1&k_2-\lambda\end{vmatrix}=-\lambda\left(k_2-\lambda\right)-k_1=\lambda^2-K_2\lambda-k_1=0
\end{aligned}

\begin{aligned}
\lambda^2-K_2\lambda-k_1\equiv\left(\lambda+1\right)^2=\lambda^2+2\lambda+1
\end{aligned}

\begin{aligned}
u=\begin{pmatrix}-1&-2\end{pmatrix}\begin{pmatrix}x_1\\x_2\end{pmatrix}=-x_1-2x_2
\end{aligned}