<h4><i>Пример 1. </i>Исследовать на наблюдаемость систему:</h4>
\begin{aligned}
\left\{ 
\begin{array}{cl}
\dot{x_{1}}&= \ x_{2} \\
\dot{x_{2}}&= \ \mathbb{u}
\end{array}
\right.
\end{aligned}
\begin{aligned}
y = x_{1} = Hx
\end{aligned}

In [9]:
import numpy as np
from numpy import linalg as LA

In [10]:
A = np.array([ 
    [0, 1], 
    [0, 0] 
])
B = np.array([ 
    [0], 
    [1] 
])
H = np.array([ 1, 0 ])

In [11]:
AB = A.dot(B)
AB

array([[1],
       [0]])

In [12]:
# K = (B, AB)

K = np.array([
    [ B[0][0], AB[0][0] ],
    [ B[1][0], AB[1][0] ]
])
K

array([[0, 1],
       [1, 0]])

In [13]:
LA.det(K)

-1.0

In [14]:
LA.matrix_rank(K)

2

<h4>проверка на наблюдаемость:</h4>

In [15]:
HA = H.dot(A)
HA

array([0, 1])

In [16]:
res_m = np.array([
    H,
    HA
])
res_m

array([[1, 0],
       [0, 1]])

In [19]:
LA.matrix_rank(res_m)

2

In [20]:
LA.det(res_m)

1.0

<i>Det != 0; rank = n. Система наблюдаема по критерию Калмана.</i>

<h4>Пример 2.</h4>