*X1 = X1 + 2X2 + X3 + U,
*X2 = X2 + 3X3 - U,
*X3 = X1 - X2 - X3
n = 3
X = (X1, X2, X3) => R**3; U є R; <=> X = Ax + Bu
K = (B, AB, A2B .... An-1B) = rank = n
det K != 0

In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
A = np.array([ 
    [1, 2, 1],
    [0, 1, 3],
    [1, -1, -1] 
])
A

array([[ 1,  2,  1],
       [ 0,  1,  3],
       [ 1, -1, -1]])

In [3]:
B = np.array([ [1], [-1], [0] ])
B

array([[ 1],
       [-1],
       [ 0]])

In [4]:
AB = A.dot(B)
AB

array([[-1],
       [-1],
       [ 2]])

In [5]:
A2B = A.dot(AB)
A2B

array([[-1],
       [ 5],
       [-2]])

In [7]:
K = np.array([
    [ B[0][0], AB[0][0], A2B[0][0] ],
    [ B[1][0], AB[1][0], A2B[1][0] ],
    [ B[2][0], AB[2][0], A2B[2][0] ]
])
K

array([[ 1, -1, -1],
       [-1, -1,  5],
       [ 0,  2, -2]])

In [8]:
LA.det(K)

-4.0

In [10]:
LA.matrix_rank(K)

3