<h4>Привести систему к канонической форме Бруновского: </h4>

\begin{aligned}
\left\{ 
\begin{array}{cl}
\dot{x_{1}}&= \ x_{2} + 2x_{3} \\
\dot{x_{2}}&= \ -x_{1} + x_{2} \\
\dot{x_{3}}&= \ x_{2} + \mathbb{u}
\end{array}
\right.
\end{aligned}
\begin{aligned}
\dot{x}=A_{x}+B_{\mathbb{u}}, x \in \mathbb{R^3}
\end{aligned}

In [1]:
import numpy as np
from numpy import linalg as LA

In [4]:
A = np.array([ [ 0, 1, 2], [-1, 1, 0], [ 0, 1, 0] ])
A

array([[ 0,  1,  2],
       [-1,  1,  0],
       [ 0,  1,  0]])

In [6]:
B = np.array([ [0], [0], [1] ])
B

array([[0],
       [0],
       [1]])

In [7]:
AB = A.dot(B)
AB

array([[2],
       [0],
       [0]])

In [10]:
A2B = A.dot(AB)
A2B

array([[ 0],
       [-2],
       [ 0]])

In [11]:
K = np.array([ 
    [ B[0][0], AB[0][0], A2B[0][0] ],
    [ B[1][0], AB[1][0], A2B[1][0] ],
    [ B[2][0], AB[2][0], A2B[2][0] ]
])
K

array([[ 0,  2,  0],
       [ 0,  0, -2],
       [ 1,  0,  0]])

In [12]:
LA.det(K)

-4.0

In [13]:
LA.matrix_rank(K)

3

In [14]:
# c = (c1, c2, c3) != 0
# cB = 0, cAB = 0
c = np.array([ 0, 1, 0 ])
c

array([0, 1, 0])

\begin{aligned}
\bar{x} = D_{x}
\end{aligned}
\begin{aligned}
\bar{\mathbb{u}} = \alpha_{\mathbb{u}} + \beta_{x}
\end{aligned}
\begin{aligned}
D = \begin{pmatrix}
c \\
cA \\
cA^2
\end{pmatrix}
\end{aligned}
\begin{aligned}
\alpha = cA^2B;\ \beta = cA^3
\end{aligned}

In [16]:
cA = c.dot(A)
cA

array([-1,  1,  0])

In [17]:
cA2 = cA.dot(A)
cA2

array([-1,  0, -2])

In [18]:
D = np.array([ c, cA, cA2 ])
D

array([[ 0,  1,  0],
       [-1,  1,  0],
       [-1,  0, -2]])

In [21]:
alpha = cA2.dot(B)
alpha

array([-2])

In [22]:
beta = cA2.dot(A)
beta

array([ 0, -3, -2])

\begin{aligned}
\bar{x} = D_{x}, \ \bar{\mathbb{u}} = -2\mathbb{u} -3x_{2} - 2x_{3}
\end{aligned}