<h4>Стабилизация линейных систем с наблюдателем в цепи обратной связи</h4>

<h5>1. Найти матрицу К как решение задачи стабилизации по состоянию (лекция 5)</h5>

<h5>2. Найти матрицу F для построения наблюдателя Луенбергера (лекция 6)</h5>

<h6>Дано: матрицы A, B, H</h6>
<h6>Найти матрицы K, F из условий гурвицевости матриц</h6>
<h6>A + BK</h6>
<h6>A - FH</h6>

<h6>Матрица М называется гурвицевой, если все собстенные значения этой матрицы имеют отрицательные вещественные части</h6>

\begin{aligned}
\left\{ \begin{array}{cl}
\dot{x_1} & = \ 2x_1-x_2 \\
\dot{x_2} & = \ x_2 -x_1 \\
\dot{x_3} & = \ x_1 + u
\end{array} \right.
\end{aligned}

\begin{aligned}
y = x_1 + x_2
\end{aligned}

\begin{aligned}
\dot{x} = Ax + Bu
\end{aligned}
\begin{aligned}
y=Hx
\end{aligned}

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([
    [2, -1, 0],
    [-1, 0, 1],
    [1, 0, 0]
])
A

array([[ 2, -1,  0],
       [-1,  0,  1],
       [ 1,  0,  0]])

In [3]:
B = np.array([ [0], [0], [1] ])
B

array([[0],
       [0],
       [1]])

In [9]:
H = np.array([ [1, 1, 0] ])
H

array([[1, 1, 0]])

\begin{aligned}
K = \left( k_1, k_2, k_3 \right)
\end{aligned}
\begin{aligned}
\hat{A} = A + BK = \begin{pmatrix}
2    & -1  & 0 \\
-1   &  0  & 1 \\
1+k_1&  k_2& k_3
\end{pmatrix}
\end{aligned}

\begin{aligned}
P\left(\lambda\right)=\left| A+BK -\lambda I \right| = \begin{pmatrix}
2-\lambda & -1  & 0 \\
-1 & -\lambda & 1 \\
1+k_1 & k_2  & k_3-\lambda
\end{pmatrix} = \left(2-\lambda\right)\lambda \left(\lambda-k_3\right)-1-k_1-k_2 \left( 2-\lambda \right) + \lambda - k_3 = \left(2\lambda - \lambda^2\right)\left(\lambda-k_3\right)-1-k_1-2k_2-k_3+\left(1-k_2\right)\lambda=
\end{aligned}

\begin{aligned}
= 2\lambda^2-\lambda^3 -2k_3\lambda+k_3\lambda^2 -1-k_1-2k_2-k_3+\left(1-k_2\right)\lambda=
\end{aligned}

\begin{aligned}
P\left(\lambda\right)=P_3\lambda^3+P_2\lambda^2+P_1\lambda+P_0
\end{aligned}
\begin{aligned}
P_3 = -1 \\
P_2 = 2 + K_3 \\
P_1 = 1-k_2-2k_3 \\
P_0 = -1-k_1-2k_2-k_3
\end{aligned}

\begin{aligned}
P\left(\lambda\right)\equiv\pm\left(\lambda+1\right)^3\equiv\pm\left(\lambda^3+3\lambda^2+3\lambda+1\right)\equiv-\lambda^3-3\lambda^2-3\lambda-1
\end{aligned}

\begin{aligned}
P_3=-1 \\
P_2=-3 \\
P_1=3  \\
P_0=-1 \\
k_3 = -5 \\
k_2 = 8 \\
k_1 = -11
\end{aligned}

In [5]:
K = np.array([ [-11, 8, -5] ])
K

array([[-11,   8,  -5]])

In [6]:
hatA = A + B.dot(K)
hatA

array([[  2,  -1,   0],
       [ -1,   0,   1],
       [-10,   8,  -5]])

<h6>Найдем матрицу F:</h6>

\begin{aligned}
F = \begin{pmatrix}
f_1 \\
f_2 \\
f_3
\end{pmatrix}
\end{aligned}

\begin{aligned}
\left| A-FH-\lambda I\right|\equiv\pm\left(\lambda+1\right)^3
\end{aligned}

\begin{aligned}
\begin{pmatrix}
2-f_1-\lambda & -1-f_1       & 0        \\
-1-f_2        & -f_2-\lambda & 1        \\
1-f_3         & -f_3         & -\lambda
\end{pmatrix}
\end{aligned}

\begin{aligned}
3f_2\lambda + 2\lambda^2 - f_1\lambda^2 - \lambda^2 f_2 - \lambda^3 - \lambda f_3 + \lambda - 1 + 3f_3 + f_1\lambda - f_1
\end{aligned}

In [39]:
l = -1
I = np.eye(3, dtype='int')
lI = I.dot(l)

F = np.array([ [1],[0],[-2] ])

FH = F.dot(H)

P_l = A - FH - lI
LA.det(P_l)

-10.000000000000002