<h4>Уравнение затухающих колебаний физического маятника с приложенным управлением:</h4>

\begin{aligned}
\ddot{\varphi}=-\frac{g}{l}\sin\varphi-K\dot{\varphi}+\mathbb{U}
\end{aligned}

<h4>Уравнение движения математического маятника:</h4> 
<h6>( пренебрегаем точностью синуса угла, заменяем на угол согласно ур-ю 2 )</h6>

\begin{aligned}
\sin\varphi\approx\varphi+\mathbb{O}\left(\varphi^{2}\right)
\end{aligned}

\begin{aligned}
\ddot{\varphi}=-\frac{g}{l}\varphi-K\dot{\varphi}+\mathbb{U}
\end{aligned}

<h4>Согласно 2 закона Ньютона F=ma получим:</h4>

\begin{aligned}
\left\{ 
\begin{array}{cl} 
a_{\tau} & = \ l\ddot{\varphi} \\
a_{n} & = \ \frac{v^2}{l} = \frac{l^2\dot{\varphi}^2}{l} = l\dot{\varphi}^2 
\end{array}
\right.
\end{aligned}

\begin{aligned}
ma_{\tau}=F\tau=\mathbb{U}-mg\sin\varphi
\end{aligned}

\begin{aligned}
\mathbb{U}=0
\end{aligned}
\begin{aligned}
ml\ddot{\varphi}=-mg\sin\varphi
\end{aligned}
\begin{aligned}
\varphi=-\frac{g}{l}\sin\varphi
\end{aligned}

<h4>Сформируем условия задачи для проверки системы на управляемость:</h4>

\begin{aligned}
x = \binom{x_{1}}{x_{2}}:x_{1}=\varphi,x_{2}=\dot{\varphi};
\end{aligned}
\begin{aligned}
\left\{ 
\begin{array}{cl} 
\dot{x_{1}}&=x_{2} \\
\dot{x_{2}}&=-\frac{g}{l}x_{1}-Kx_{2}+\mathbb{U}
\end{array}
\right.
\end{aligned}
\begin{aligned}
\dot{x}=A_{x}+B_{\mathbb{U}}
\end{aligned}

In [1]:
import numpy as np
import numpy.linalg as LA
from scipy.constants import g

In [18]:
# n = 2
l = 20     # length
K = 0.08   # constant of friction
n_gl = -(g/l)
n_gl

-0.49033249999999995

In [21]:
A = np.array([
    [0,     1],
    [n_gl, -K]
])
A

array([[ 0.       ,  1.       ],
       [-0.4903325, -0.08     ]])

In [22]:
B = np.array([[0],[1]])
B

array([[0],
       [1]])

In [23]:
AB = A.dot(B)
AB

array([[ 1.  ],
       [-0.08]])

In [24]:
K_m = np.array([
    [B[0][0], AB[0][0]],
    [B[1][0], AB[1][0]]
])
K_m

array([[ 0.  ,  1.  ],
       [ 1.  , -0.08]])

In [25]:
LA.det(K_m)

-1.0

In [26]:
LA.matrix_rank(K_m)

2

<h4>Вывод: определитель != 0 и ранг = 2, система управляема.</h4>