<h4>Алгоритм построения наблюдателя Луенбергера:</h4>
<h5>1. записать матрицу: </h5>
\begin{aligned}
F = (f_{1},f_{2},...,f_{n})^T
\end{aligned}

<h5>2. Вычислить матрицу W = A - FH</h5>

<h5>3. Записать характеристический многочлен матрицы W:</h5>
\begin{aligned}
P\left(\lambda\right)=\left| W-\lambda I \right|
\end{aligned}

<h5>4. Коэффициенты многочлена P зависят от f1,f2,...,fn.</h5>
<h5>Подобрать f1,f2,...,fn так, чтобы все корни уравнения:</h5>
\begin{aligned}
P\left(\lambda\right)=0
\end{aligned}
<h5>обладали свойством:</h5>
\begin{aligned}
Re\left(\lambda_j\right)<0,\text{  }& j=1,2,...,n
\end{aligned}

<h5>В частности, можно определить f1, ..., fn из условия:  </h5>
\begin{aligned}
P\left( \lambda \right)\equiv \pm \left( \lambda+1 \right)^n
\end{aligned}

<h5>Тогда система:</h5>
\begin{aligned}
\dot{Z}= \left( A-FH \right)Z+Bu+Fy
\end{aligned}
<h5>называется наблюдателем Луенбергера для системы:</h5>

<h5>(3)</h5>
\begin{aligned}
\dot{x}=Ax+Bu,\text{  }x\in R^n, u\in R^m
\end{aligned}
<h5>(4)</h5>
\begin{aligned}
y=Hx,\text{  }y \in R^r
\end{aligned}

<h4>Пример:</h4>
\begin{aligned}
\left\{ \begin{array}{cl}
\dot{x_1} & = x_2 \\
\dot{x_2} & = x_3 \\
\dot{x_3} & = u
\end{array} \right.
\end{aligned}

\begin{aligned}
y=x_1
\end{aligned}
\begin{aligned}
\dot{x}=Ax+Bu
\end{aligned}
\begin{aligned}
y=Hx
\end{aligned}

In [2]:
import numpy as np
from numpy import linalg as LA

In [3]:
A = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [0, 0, 0]
])
A

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [4]:
B = np.array([
    [0],
    [0],
    [1]
])
B

array([[0],
       [0],
       [1]])

In [5]:
H = np.array([ [1, 0, 0] ])
H

array([[1, 0, 0]])

\begin{aligned}
F = \begin{pmatrix}
f_{1} \\
f_{2} \\
f_{3}
\end{pmatrix}
\end{aligned}

\begin{aligned}
W=A-\begin{pmatrix}f_1 \\f_2 \\f_3\end{pmatrix}\left(1, 0, 0 \right)=\begin{pmatrix}
-f_1 &1  &0  \\
-f_2 &0  &1  \\
-f_3 &0  &0 
\end{pmatrix}
\end{aligned}

\begin{aligned}
P\left( \lambda \right) = \begin{pmatrix}
-f_1-\lambda & 1        & 0  \\
-f_2         & -\lambda & 1  \\
-f_3         & 0        & -\lambda 
\end{pmatrix} 
= \lambda^2 \left( \lambda + f_1 \right)-f_3-f_2\lambda
= -\lambda^3 - f_1\lambda^2-f_2\lambda-f_3
\end{aligned}

\begin{aligned}
P\left(\lambda\right)\equiv-\left(\lambda+1\right)^3\equiv-\lambda^3-3\lambda^2-3\lambda-1
\end{aligned}

\begin{aligned}
f_1 = 3,
f_2 = 3,
f_3 = 1
\end{aligned}

In [28]:
F = np.array([
    [3],
    [3],
    [1]
])
F

array([[3],
       [3],
       [1]])

In [29]:
W = A - F.dot(H)
W

array([[-3,  1,  0],
       [-3,  0,  1],
       [-1,  0,  0]])

In [32]:
LA.det(W)

-1.0

In [37]:
lmbda = 0
I = np.eye(3, dtype='int')
Plmbda = W - lmbda * I
Plmbda

array([[-3,  1,  0],
       [-3,  0,  1],
       [-1,  0,  0]])