<p> *x1 = x1 + 2x2 - x3 - u1 </p>
<p> *x2 = -x1 + x4 + u1 + u2 </p>
<p> *x3 = 5x1 - 3x2 - x3 + x4 + u1 - 2u2 </p>
<p> *x4 = -x1 - x2 - x3 + x4 </p>

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[1, 2, -1, 0], [-1, 0, 0, 1], [5, -3, -1, 1], [-1, -1, -1, 1]])
A

array([[ 1,  2, -1,  0],
       [-1,  0,  0,  1],
       [ 5, -3, -1,  1],
       [-1, -1, -1,  1]])

In [3]:
B = np.array([[-1, 0], [1, 1], [1, -2], [0, 0]])
B

array([[-1,  0],
       [ 1,  1],
       [ 1, -2],
       [ 0,  0]])

In [4]:
AB = A.dot(B)
AB

array([[ 0,  4],
       [ 1,  0],
       [-9, -1],
       [-1,  1]])

In [5]:
A2B = A.dot(AB)
A2B

array([[11,  5],
       [-1, -3],
       [ 5, 22],
       [ 7, -2]])

In [6]:
A3B = A.dot(A2B)
A3B

array([[  4, -23],
       [ -4,  -7],
       [ 60,  10],
       [ -8, -26]])

In [7]:
K = np.array([
    [B[0][0], B[0][1], AB[0][0], AB[0][1], A2B[0][0], A2B[0][1], A3B[0][0], A3B[0][1]],
    [B[1][0], B[1][1], AB[1][0], AB[1][1], A2B[1][0], A2B[1][1], A3B[1][0], A3B[1][1]],
    [B[2][0], B[2][1], AB[2][0], AB[2][1], A2B[2][0], A2B[2][1], A3B[2][0], A3B[2][1]],
    [B[3][0], B[3][1], AB[3][0], AB[3][1], A2B[3][0], A2B[3][1], A3B[3][0], A3B[3][1]],
])
K

array([[ -1,   0,   0,   4,  11,   5,   4, -23],
       [  1,   1,   1,   0,  -1,  -3,  -4,  -7],
       [  1,  -2,  -9,  -1,   5,  22,  60,  10],
       [  0,   0,  -1,   1,   7,  -2,  -8, -26]])

In [8]:
LA.matrix_rank(K)

4

In [9]:
# Если все элементы строки или столбца можно представить как сумму двух слагаемых, 
# то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

s1 = np.array([
    [B[0][0], AB[0][0], A2B[0][0], A3B[0][0]],
    [B[1][0], AB[1][0], A2B[1][0], A3B[1][0]],
    [B[2][0], AB[2][0], A2B[2][0], A3B[2][0]],
    [B[3][0], AB[3][0], A2B[3][0], A3B[3][0]]
])
s1

array([[-1,  0, 11,  4],
       [ 1,  1, -1, -4],
       [ 1, -9,  5, 60],
       [ 0, -1,  7, -8]])

In [10]:
s2 = np.array([
    [B[0][1], AB[0][1], A2B[0][1], A3B[0][1]],
    [B[1][1], AB[1][1], A2B[1][1], A3B[1][1]],
    [B[2][1], AB[2][1], A2B[2][1], A3B[2][1]],
    [B[3][1], AB[3][1], A2B[3][1], A3B[3][1]]
])
s2

array([[  0,   4,   5, -23],
       [  1,   0,  -3,  -7],
       [ -2,  -1,  22,  10],
       [  0,   1,  -2, -26]])

In [11]:
LA.det(s1) + LA.det(s2)

3460.0000000000005

In [12]:
(LA.det(s1) + LA.det(s2)) > 0

True

In [13]:
s3 = np.array([
    [-1, 4, 16, 19],
    [2, 1, -4, -11],
    [-1, -10, 27, 70],
    [0, 0, 5, -34]
])
s3

array([[ -1,   4,  16,  19],
       [  2,   1,  -4, -11],
       [ -1, -10,  27,  70],
       [  0,   0,   5, -34]])

In [15]:
LA.det(s3) + LA.det(s3)

41758.000000000044