In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([
    [0, 0, 0],
    [1, 0, 1],
    [0, 0, 0]
]) 
A

array([[0, 0, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [3]:
B = np.array([
    [1, 0],
    [1, 1],
    [0, 1]
])
B

array([[1, 0],
       [1, 1],
       [0, 1]])

In [4]:
AB = A.dot(B)
AB

array([[0, 0],
       [1, 1],
       [0, 0]])

In [5]:
A2B = A.dot(AB)
A2B

array([[0, 0],
       [0, 0],
       [0, 0]])

In [12]:
K = np.array([
    [ B[0][0], B[0][1], AB[0][0], AB[0][1], A2B[0][0], A2B[0][1] ],
    [ B[1][0], B[1][1], AB[1][0], AB[1][1], A2B[1][0], A2B[1][1] ],
    [ B[2][0], B[2][1], AB[2][0], AB[2][1], A2B[2][0], A2B[2][1] ]
])
K

array([[1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [13]:
LA.matrix_rank(K)

3

In [16]:
K2 = np.array([
    [B[0][0], AB[0][0], A2B[0][0]],
    [B[1][0], AB[1][0], A2B[1][0]],
    [B[2][0], AB[2][0], A2B[2][0]]
])

LA.det(K2)

0.0

In [18]:
K2

array([[1, 0, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [17]:
K3 = np.array([
    [B[0][1], AB[0][1], A2B[0][1]],
    [B[1][1], AB[1][1], A2B[1][1]],
    [B[2][1], AB[2][1], A2B[2][1]]
])

LA.det(K3)

0.0

In [19]:
K3

array([[0, 0, 0],
       [1, 1, 0],
       [1, 0, 0]])

In [20]:
K4 = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 0, 0]
])

LA.det(K4)

0.0