<h4>Привести до канонічної форми Бруновського систему:</h4>

\begin{aligned}
\left\{ \begin{array}{cl}
\dot{x_1} & = \ x_1 + 2x_3   \\
\dot{x_2} & = \ -x_1-x_2     \\
\dot{x_3} & = \ -x_1+5x_3-2u
\end{array} \right.
\end{aligned}

In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, 0, 2],
    [-1, -2, 0],
    [-1, 0, 5]
])
A

array([[ 1,  0,  2],
       [-1, -2,  0],
       [-1,  0,  5]])

In [4]:
B = np.array([ [0],[0],[-2] ])
B

array([[ 0],
       [ 0],
       [-2]])

In [25]:
# cB = cAB = 0
c = np.array([ 0, 1, 0 ])

In [26]:
c.dot(B)

array([0])

In [27]:
c.dot(A.dot(B))

array([0])

In [28]:
cA = c.dot(A)
cA

array([-1, -2,  0])

In [29]:
cA2 = cA.dot(A)
cA2

array([ 1,  4, -2])

In [30]:
D = np.array([ c, cA, cA2 ])
D

array([[ 0,  1,  0],
       [-1, -2,  0],
       [ 1,  4, -2]])

In [31]:
alpha = cA2.dot(B)
alpha

array([4])

In [32]:
beta = cA2.dot(A)
beta

array([-1, -8, -8])

\begin{aligned}
\bar{x}=Dx, \ \bar{u}=4u-x_1-8x_2-8x_3
\end{aligned}