<h4>Перевірити ранговий критерій керованості Калмана для системи:</h4>
\begin{aligned}
\left\{ \begin{array}{cl}
\dot{x_1} & = \ -2x_2-x_3   \\
\dot{x_2} & = \ x_1+x_2+2u  \\
\dot{x_3} & = \ -7x_1+2x_3-u
\end{array} \right.
\end{aligned}

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([
    [0, -2, -1],
    [1, 1, 0],
    [-7, 0, 2]
])
A

array([[ 0, -2, -1],
       [ 1,  1,  0],
       [-7,  0,  2]])

In [3]:
B = np.array([ [0], [2], [-1] ])
B

array([[ 0],
       [ 2],
       [-1]])

In [4]:
AB = A.dot(B)
AB

array([[-3],
       [ 2],
       [-2]])

In [5]:
A2B = A.dot(AB)
A2B

array([[-2],
       [-1],
       [17]])

In [6]:
K = np.array([ 
    [B[0][0], AB[0][0], A2B[0][0]], # 0
    [B[1][0], AB[1][0], A2B[1][0]], # 1
    [B[2][0], AB[2][0], A2B[2][0]], # 2
])
K

array([[ 0, -3, -2],
       [ 2,  2, -1],
       [-1, -2, 17]])

In [7]:
LA.matrix_rank(K)

3

In [8]:
LA.det(K)

103.00000000000001