# COURSE: Master math by coding in Python
## SECTION: Algebra 1

#### https://www.udemy.com/course/math-with-python/?couponCode=MXC-DISC4ALL
#### INSTRUCTOR: sincxpress.com

Note about this code: Each video in this section of the course corresponds to a section of code below. Please note that this code roughly matches the code shown in the live recording, but is not exactly the same -- the variable names, order of lines, and parameters may be slightly different. 

In [5]:
# It's generally good practice to import all required modules at the top of the script!
import sympy as sym
import numpy as np
from IPython.display import display, Math

# VIDEO: Solving for x

In [6]:
x = sym.symbols('x')

# the expression we want to solve is 2x+4=9
expr = 2*x + 4 -9

sym.solve(expr,x)

[5/2]

In [7]:
# make it look a bit nicer

sol = sym.solve(expr,x)

display('The solution to %s is %g'%(expr,sol[0]))

# or
display(Math('\\text{The solution to }%s\\text{ is x=}%g' %(sym.latex(expr),sol[0])))

'The solution to 2*x - 5 is 2.5'

<IPython.core.display.Math object>

In [8]:
# can input the equation directly into the solve function
sym.solve(x**2 - 4,x)

[-2, 2]

In [9]:
# notice the solution is stored as a list, with one solution per element
sol = sym.solve(x**2 - 4,x)

print( type(sol) )
print( len(sol) )

<class 'list'>
2


In [10]:
# we can print them all out:
for i in range(0,len(sol)):
    print('Solution #' + str(i+1) + ' is ' + str(sol[i]))


Solution #1 is -2
Solution #2 is 2


In [11]:
y = sym.symbols('y')

expr = x/4 - x*y + 5

print( "Solved for x: " + str(sym.solve(expr,x)[0]) )
print( "Solved for y: " + str(sym.solve(expr,y)) )


Solved for x: 20/(4*y - 1)
Solved for y: [(x + 20)/(4*x)]


### Exercises

In [12]:
# 1)
# simplify and solve for q
q = sym.symbols('q')
eq = 3*q + 4/q + 3 - 5*q - 1/q - 1

display(Math(sym.latex(eq.simplify()))) 
display(Math('q='+sym.latex(sym.solve(eq,q))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [13]:
# 2)
eq = 2*q + 3*q**2 - 5/q - 4/q**3

display(Math(sym.latex(eq)))
display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq)))) # puts into p/q form with integer coefficients

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [14]:
# 3)
# simplify this expression. confirm on your own using paper-and-pencil
expr = (sym.sqrt(3) + sym.sqrt(15)*q) / (sym.sqrt(2) + sym.sqrt(10)*q)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.simplify(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [15]:
sym.simplify( expr.subs(q,10) )

sqrt(6)/2

In [16]:
expr.subs(q,10).evalf()

1.22474487139159

# VIDEO: Expanding terms

In [17]:
# define our terms
from sympy.abc import x

term1 = (4*x + 5)
term2 = x

print( term1*term2 )
print( sym.expand(term1*term2) )
print( Math(sym.latex(sym.expand(term1*term2)) ))

x*(4*x + 5)
4*x**2 + 5*x
<IPython.core.display.Math object>


In [18]:
term3 = x - 7 # note that parentheses are not necessary!

display(Math( sym.latex(term1*term3) ))
display(Math( sym.latex( sym.expand(term1*term3) )))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [19]:
# with two variables
y = sym.symbols('y')

expr = x*(2*y**2 - 5**x/x)
sym.expand(expr)

-5**x + 2*x*y**2

In [20]:
# three expressions and three variables!!
# but first, what variables have we already created??
%whos


Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x1080ade10>
eq         Add         3*q**2 + 2*q - 5/q - 4/q**3
expr       Mul         x*(-5**x/x + 2*y**2)
i          int         1
np         module      <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
os         module      <module 'os' from '/opt/h<...>10/lib/python3.10/os.py'>
q          Symbol      q
sol        list        n=2
sym        module      <module 'sympy' from '/op<...>kages/sympy/__init__.py'>
sys        module      <module 'sys' (built-in)>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
x          Symbol      x
y          Symbol      y


In [21]:
z = sym.symbols('z')

term1 = (3 + x)
term2 = (y - 4*z)
term3 = (5/z + 3*x)

display(Math(sym.latex(term1*term2*term3)))
display(Math(sym.latex(sym.expand(term1*term2*term3))))
display(Math(sym.latex(sym.simplify(sym.expand(term1*term2*term3)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### Exercises

In [22]:
# a function of two variables
Fxy = (4+x)*(2-y)
print(Fxy.subs({x:2,y:-2}))

24


In [23]:
numrange = range(0,3)
for i in numrange:
    for j in numrange:
        print('When x=%g and y=%g, f(x,y)=%g' %(i,j,Fxy.subs({x:i,y:j})) )

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


# VIDEO: Creating and accessing matrices with numpy

In [24]:
A = np.array( [ [1,2],[3,4] ] )
print(A)

# make it look nicer
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [25]:
# initializing a matrix with zeros

numrange = range(0,5)

mat = np.zeros([len(numrange),len(numrange)])
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# populating matrices using row-col indexing

mat[0,1] = 1
# mat[5,8] = 4
mat

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# can also use variables for indices
i = 2
j = 1
mat[i,j] = 4.5

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [28]:
# now use a for-loop

numrange = range(0,3)
for i in numrange:
    for j in numrange:
        mat[i][j] = (-1)**(i+j)

mat

array([[ 1., -1.,  1.,  0.,  0.],
       [-1.,  1., -1.,  0.,  0.],
       [ 1., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### Exercise

In [29]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)

numrange = range(0,3)

funout = np.zeros((len(numrange),len(numrange)))

for i in numrange:
    for j in numrange:
        funout[i,j] = Fxy.subs({x:i,y:j})

display(Math(sym.latex(sym.sympify(funout))))

<IPython.core.display.Math object>

### Exercise: Create a multiplication table

In [30]:
nums = range(1,11)

multmat = np.zeros((len(nums),len(nums)),dtype=int)

for i in nums:
    for j in nums:
        multmat[i-1,j-1] = i*j

        
display(Math(sym.latex(sym.sympify(multmat)))) # no display without display

x = 3

<IPython.core.display.Math object>

# VIDEO: Associative, commutative, and distributive properties

### Associative

In [31]:
from sympy.abc import x,y

expr1 = x*(4*y)
expr2 = (x*4)*y

# show that two equations are equal by subtracting them!
expr1 - expr2

0

### Commutative

In [32]:
# create three expressions
e1 = x*4*y
e2 = 4*x*y
e3 = y*x*4

In [33]:
# quick reminder about substitution in sympy
display( e1.subs(x,3) )

# multiple subsitutions
e3.subs({x:2,y:3})

12*y

24

In [34]:
# now back to the task!
print( e1.subs({x:3,y:4}) )
print( e2.subs({x:3,y:4}) )
print( e3.subs({x:3,y:4}) )

48
48
48


### Distributive

In [35]:
# another way of creating symbolic variables
from sympy.abc import a, b, c, d

expr = (a+b)*(c+d)
expr

(a + b)*(c + d)

In [36]:
sym.expand(expr)

a*c + a*d + b*c + b*d

In [37]:
sym.expand( (a+d)*(a-d) )

a**2 - d**2

In [38]:
# embedding expressions
a,x,y,z = sym.symbols('a,x,y,z')

x = 3*y + z
a = 4*x

display(a)

12*y + 4*z

### Exercises

In [39]:
# with these two expressions, show that the commutative rule applies

w,x,y,z = sym.symbols('w,x,y,z')

x = w*(4-w)+1/w**2*(1+w)
expr1 = x*(y+z)
expr2 = 3/x+x**2

display(Math(sym.latex(expr1*expr2)))
display(Math(sym.latex(sym.simplify(expr1*expr2))))
display(Math(sym.latex(expr2*expr1 - expr1*expr2)))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

# VIDEO: Creating and working with Python lists

In [40]:
# a list is a collection of things, and created using brackets []
# A simple example is a list of numbers

lst = [1,3,4,7]
print( lst )
print(type(lst))

[1, 3, 4, 7]
<class 'list'>


In [41]:
# you can access individual list elements
lst[2]

4

In [42]:
# -1 is for the final element
lst[-1]

7

In [43]:
# "slicing"

# print the first N list items
N = 2
lst[:N]


[1, 3]

In [44]:
# print the last k items
k = 2
lst[-k:]


[4, 7]

In [45]:
# print items n through k
lst = [1,2,3,4,5,6,7,8,9]

n = 3
k = 7

lst[n-1:k]


[3, 4, 5, 6, 7]

In [46]:
# a list of strings
name = ['hello','my','name','is','Mike']

# access each element using a for-loop
for i in range(len(name)):
    print(name[i])

hello
my
name
is
Mike


In [47]:
# simpler!
for i in name:
    print(i)

hello
my
name
is
Mike


In [48]:
# lists can also hold more than one variable type
alist = [1,2,'cookies',[4,5]]

for i in alist:
    print(i)

1
2
cookies
[4, 5]


In [49]:
# getting items from a list-within-a-list

print( alist[-1] )

print( alist[-1][1] )

[4, 5]
5


In [50]:
# the term 'list' is reserved:
alist2 = list( (1,2,'cookies',[4,5]) )

for i in alist2:
    print(i)

1
2
cookies
[4, 5]


In [51]:
# importantly, we will use lists for sympy expressions!
# list_of_expressions
expr_list = [ 4*x**2 , 3+x , (1-x)/(1+x) ]

### Exercises

In [52]:
# use sympy to expand and simplify these expressions
x = sym.symbols('x')

e1 = 2*x + x*(4-6*x) + x
e2 = -x * (2/x + 4/(x**2)) + (4+x)/(4*x)
e3 = (x + 3)*(x-3)*x*(1/(9*x))

# make a list of the expressions
exprs = [e1,e2,e3]

for i in range(0,3):
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s' %(sym.latex(exprs[i]),sym.latex(sym.expand(exprs[i])))))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

# VIDEO: More on "slicing" in Python

In [53]:
# create an array (vector) of numbers
vec = [10,11,12,13,14,15,16,17,18,19,20]
# or
vec = list(range(10,21))

print(vec)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [54]:
# indexing a single item
vec[2]

12

In [55]:
# indexing multiple items (aka slicing)
vec[2:4]

[12, 13]

In [56]:
# from one element to the end
vec[4:]

[14, 15, 16, 17, 18, 19, 20]

In [57]:
# from the first element to a specific element
vec[:3]

[10, 11, 12]

In [58]:
# the last element
vec[-1]

# penultimate element
vec[-2]


19

In [59]:
# from the end to the beginning
vec[::-1]

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]

In [60]:
# with non-1 stepping
vec[0:5:2]

[10, 12, 14]

# VIDEO: Greatest common denominator

In [61]:
# reminder: GCD is the largest integer that can divide both numbers without a remainder

# we'll use the math package for this!
import math

math.gcd(95,100)

5

In [65]:
# GCD is defined for integers!
math.gcd(1,3)

1

In [63]:
math.gcd(0,3)

3

In [ ]:
# application: reduce fraction to lowest term

a = 16
b = 88

fact = math.gcd(a,b)

display(Math('\\frac{%g}{%g} \\quad = \\quad \\frac{%g}{%g} \\times \\frac{%g}{%g}' %(a,b,a/fact,b/fact,fact,fact)))


### Exercises

In [ ]:
# show this property using symbols, and give an example with numbers.

# gcd(m·a, m·b) = m·gcd(a, b)

a,b,c = sym.symbols('a,b,c')

display( sym.gcd(c*a,c*b) )
display( c*sym.gcd(a,b) )


# now with real numbers
a = 5
b = 6
c = 7
display( math.gcd(c*a,c*b) )
display( c*math.gcd(a,b))


In [ ]:
# double loop and store in matrix
import numpy as np

N = 10
gcdMat = np.zeros((10,15))+99

for i in range(0,10):
    for j in range(0,15):
        gcdMat[i,j] = math.gcd(i+1,j+1)
        
display(Math(sym.latex(sym.sympify(gcdMat))))

# VIDEO: Introduction to dictionaries

In [ ]:
# create a dictionary
D = dict(fruit=['banana','apple'],numbers=[1,3,4,2,5])

print(D)

In [ ]:
# list the "keys"
D.keys()

In [ ]:
# get the information from the numbers
D['numbers']

In [ ]:
# or this way
D.get('fruit')[0]

In [ ]:
len(D)

In [ ]:
# print out all information in a loop!
for items in D.keys(): # .keys() is implied!
    print(D[items])

In [ ]:
# make a dictionary of equations
x,y = sym.symbols('x,y')

D = dict(eqsWithX=[x/3-6,x*2+3],eqsWithY=[y-y/4,y-5])
D.keys()

Dkeys = list(D)

# access individual keys
D[Dkeys[0]]


### Exercise

In [ ]:
# let's make a new dictionary
x,y = sym.symbols('x,y')

# count number of x's and y's in the equation
D = dict(eqsWithX=[4*x-6,x**2-9],eqsWithY=[sym.sin(y)])

# solve them in a loop
for keyi in D:
    
    print('Equations solving for ' + keyi[-1] + ':')
    
    for i in D[keyi]:
        
        fullEQ     = sym.latex(sym.sympify(i)) + ' = 0'
        middlepart = '\\quad\\quad \\Rightarrow\\quad\\quad ' + keyi[-1] + ' = '
        soln       = sym.latex(sym.solve(i))
        
        display(Math( '\\quad\\quad ' + fullEQ + middlepart + soln ))



# VIDEO: Prime factorization

In [ ]:
# factor an integer into the product of prime numbers
number = 48

# Use the sympy function factorint. The output is a dictionary!
fact_dict = sym.factorint(number)
print(fact_dict)

In [ ]:
# just print the prime numbers
primenumbers = list( fact_dict.keys() )

print('The prime factors of ' + str(number) + ' are ' + str(primenumbers))

fact_dict[primenumbers[1]]

In [ ]:
# test on prime number
sym.factorint(4)

### Exercise

In [ ]:
# loop through numbers and report whether each number is composite or prime

nums = range(2,51)
for i in nums:
    di = sym.factorint(i)
    ks = list(di.keys())
    if len(di)==1 and di[ks[0]]==1:
        print('%s is a prime number' %i)
    else:
        print('%s is a composite number with prime factors %s' %(i,list(di.keys())))


# VIDEO: Solving inequalities

In [ ]:
x = sym.symbols('x')

expr = 4*x > 8
sym.solve(expr)

In [ ]:
display(Math(sym.latex(sym.solve(expr))))

In [ ]:
sym.oo > 10000093847529345

In [ ]:
expr = (x-1)*(x+3) > 0

display(Math(sym.latex(sym.solve(expr))))

In [ ]:
# sym.solve will return the expression if not enough information

a,b,c = sym.symbols('a,b,c')

expr = a*x > b**2/c
display(Math(sym.latex(expr)))

sym.solve(expr)#,x)

In [ ]:
# a slightly richer problem
sym.solve( 2*x**2>8 )

### Exercise

In [ ]:
expr = (3*x/2) + (4-5*x)/3 <= 2 - (5*(2-x))/4

display(Math(sym.latex(expr)))
sym.solve(expr)

# VIDEO: Adding polynomials

In [ ]:
from sympy.abc import x

# straight-forward version
p1 = 2*x**3 + x**2 - x
p2 = x**3 - x**4 - 4*x**2
print( p1+p2 )

display(Math('(%s) + (%s) \quad=\quad (%s)' %(sym.latex(p1),sym.latex(p2),sym.latex(p1+p2) )))

In [ ]:
# Using the Poly class
p1 = sym.Poly(2*x**6 + x**2 - x)

p1

In [ ]:
# can implement several methods on the polynomial object
print( p1.eval(10) )

print( p1.degree() )

In [ ]:
# create a second polynomial
p2 = sym.Poly(x**3 - x**4 - .4*x**2)
print( p1-p2 )

# can also call the add method on the polynomial objects
p1.add(p2)
p1.sub(p2)
print(p1.sub(p2))
print(p1)


### Exercise

In [ ]:
# create a list of polynomials
# loop through. if order is even, sum the coeffs. if order is odd, count the number of coeffs

polys = [ sym.Poly(2*x + x**2), sym.Poly(-x**3 + 4*x), sym.Poly(x**5-x**4+1/4*x+4) ]

for poli in polys:
    if poli.degree()%2==0:
        print('The degree of %s is even, and the coefficients sum to %s.' %(poli.as_expr(),sum(poli.coeffs())))
    else:
        print('The degree of %s is odd, and there are %s coefficients.' %(poli.as_expr(),len(poli.coeffs())))

# VIDEO: Multiplying polynomials

In [ ]:
x = sym.symbols('x')

x**2 * x**3

In [ ]:
# a litte more complicated
p1 = 4*x**2 - 2*x
p2 = x**3 + 1

p1*p2

In [ ]:
# the way your math teacher would want it written out
print( sym.expand( p1*p2 ) )

display(Math(sym.latex(p1*p2)))
display(Math(sym.latex(sym.expand(p1*p2))))


In [ ]:
# check our work from the slides!
x,y = sym.symbols('x,y')

poly1 = x**5 + 2*x*y + y**2
poly2 = x - 3*x*y

poly1*poly2

In [ ]:
display(Math(sym.latex(sym.expand( poly1*poly2 ))))

### Exercise

In [ ]:
# with x's and y's, substitute before vs after multiplication
x,y = sym.symbols('x,y')

fxy = 4*x**4 - 9*y**3 - 3*x**2 + x*y**2
gxy = 4/5*y**3 - x**3 + 6*x**2*y

display(Math( '(%s)\quad\\times\quad(%s) \quad=\quad %s' %(sym.latex(fxy),sym.latex(gxy),sym.latex(sym.expand(fxy*gxy)) )))


In [ ]:
xval = 5
yval = -2

# first substitute and then multiply
fxy_subs = fxy.subs({x:xval,y:yval})
gxy_subs = gxy.subs({x:xval,y:yval})
print('Separate substitution: %s' %(fxy_subs*gxy_subs))

# multiply then substitute
fg = (fxy*gxy).subs({x:xval,y:yval})
print('Multiplied substitution: %s' %fg)


# VIDEO: Dividing by polynomials

In [ ]:
p1 = 4*x**5 - x
p2 = 2*x**3-x

display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(p1/p2)) ))
display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(sym.expand(p1/p2))) ))
display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(sym.simplify(p1/p2))) ))


In [ ]:
# with two variables
x,y = sym.symbols('x,y')

pNum = x**3 + y**2 - 4*x**2*y + x*y + 4*y
pDen = x + y

display(Math('\\frac{%s}{%s} = %s' %(sym.latex(pNum),sym.latex(pDen),sym.latex(sym.simplify(pNum/pDen))) ))


### Exercise

In [ ]:
# first, a primer on sym.fraction

num = sym.sympify(3)/sym.sympify(4)
# num = sym.sympify(3/4)

finfo = sym.fraction(num)
print(type(finfo))
print(finfo[0])

# can also isolate the numerator separately
num = sym.fraction(num)[0]
print(num)

In [ ]:

# use a loop to find the integer value of y that makes this equation simplify
pNum = x**6 + 2*x**4 + 6*x  - y
pDen = x**3 + 3


for i in range(5,16):
    
    pnum = pNum.subs({y:i})
    display(Math('\\frac{%s}{%s} = %s' %(sym.latex(pnum),sym.latex(pDen),sym.latex(sym.simplify(pnum/pDen))) ))
    
    if sym.fraction(sym.simplify(pnum/pDen))[1]==1:
        rightnumber = i

print( 'When y=%g, there is no denominator!' %rightnumber)


# VIDEO: Factoring polynomials

In [ ]:
x,y = sym.symbols('x,y')

po = x**2 + 4*x + 3
sym.factor(po)

In [ ]:
# with output

fac = sym.factor(po)
print(fac)

In [ ]:
# not every polynomial can be factored!
po = x**2 + 4*x - 3

sym.factor(po)

In [ ]:
expr = 2*y**3 - 2*y**2 - 18*y + 18
sym.factor(expr)

In [ ]:
# multiple variables
expr = 2*x**3*y - 2*x**2*y**2 + 2*x**2*y + 6*x**2 - 6*x*y + 6*x
sym.factor(expr)


### Exercise

In [ ]:
# test whether factorable, print if so.

exprs = [ x**2+4*x+3 , 2*y**2-1 , 3*y**2+12*y ]

for expri in exprs:
    tmp = str( sym.factor(expri) )
    
    if tmp.find('(')!=-1:
        display(Math('%s \\quad\\Rightarrow\\quad %s' %(sym.latex(sym.expand(expri)),sym.latex(sym.factor(expri)))))
    else:
        display(Math('%s \\quad\\Rightarrow\\quad\\text{ not factorable!}' %sym.latex(sym.expand(expri))))
    

# VIDEO: Algebra 1 BUG HUNT!

In [ ]:
# from sympy.abc import x2
x2 = sym.symbols('x2')

x2 = 4

In [ ]:
a,b,c,d = sym.symbols('a,b,c,d')

expr = 4*b + 5*a*a - c**3 + 5*d


In [ ]:
import math
math.gcd(30,50)

In [ ]:
from sympy.abc import x

expr = 4*x - 8
sym.solve(expr)

In [ ]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )
# make it look nice
display(Math(sym.latex(sym.sympify(A))))

In [ ]:
fact_dict = sym.factorint(44)
allkeys = fact_dict.keys()

for i in fact_dict:
    print('%g was present %g times.' %(i,fact_dict[i]))


In [ ]:
x,y = sym.symbols('x,y')

expr = 4*x - 5*y**2

expr.subs({x:5})


In [ ]:
# goal is to show a fraction

f = sym.sympify(5)/9

display(Math(sym.latex(f)))


In [ ]:
# print the last 3 items from a list
lst = [1,3,2,5,4,6,7,5,3,7]
lst[-3:]


In [ ]:
from sympy.abc import x,y

expr = 2*x + 4*y

# solve for y
sym.solve(expr,y)

In [ ]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )

# set the element in the second row, second column to 9
A[1,1] = 9
print(A)